#+EXPORT_EXCLUDE_TAGS: nopub
#+TITLE:Geb
* Geb
** Installation
- Recommended Groovy Version 1.7.5
- I've tested on Ubuntu Linux, other OSs to follow
- For this demo, you need Firefox installed
** Quick Start
Run this from the Groovy Console
:PROPERTIES:
:ID: a46d05d4-6d01-494d-833d-7245ccf530b9
:END:
#+BEGIN_SRC groovy
  @Grapes([
              @Grab("org.codehaus.geb:geb-core:latest.release"),
              @Grab("org.seleniumhq.selenium:selenium-firefox-driver:latest.release")
  ])
  
  import geb.Browser
  Browser.drive("http://enrollio.org") {
      assert title == "Help - About"
  }
#+END_SRC

- Grapes pulls down dependency goodies.  How it works is beyond me.
- Selenium runs under the hood, and creates an instance of the specified browser.

** Geb Test Skeleton                                                 :nopub:
:PROPERTIES:
:ID: df2c04db-2a1f-40d7-9884-f44886a25ede
:END:
#+begin_src groovy :tangle advancedTest.groovy :noweb tangle
#!/bin/env groovy
@Grapes([
              @Grab("org.codehaus.geb:geb-core:latest.release"),
              @Grab("org.seleniumhq.selenium:selenium-firefox-driver:latest.release")
])
import geb.Browser
Browser.drive("http://enrollio.org") {
    <<simpleTests>>
    <<simpleTestsAttributes>>
    <<simpleTestsRelationships>>
}
#+end_src
** CSS / Jquery like syntax for selecting HTML elements
:PROPERTIES:
:ID: 812abad7-d35f-4336-af83-b62b202e0592
:END:
#+srcname: simpleTests
#+begin_src groovy :noweb tangle
assert $("a", text:"Loooogin").size() == 0
assert $("a", text:"Login").size() == 1
#+end_src

Test results are some kind of instance of selenium's FirefoxWebElement
(if you're using Firefox Driver)

http://webdriver.googlecode.com/svn/javadoc/org/openqa/selenium/firefox/FirefoxWebElement.html

** Attribute Selectors
Say we have the following HTML:

#+begin_src html
<h3 class="reallynow">Thanks</h3>
#+end_src

Here's the Geb code we need to match the HTML.  (Both expressions match)

#+srcname: simpleTestsAttributes
#+begin_src groovy :noweb tangle
    assert $("h3", class: "reallynow", text: "Thanks").size() == 1
    assert $("h3.reallynow", text: "Thanks").size() == 1
#+end_src

** Testing Relationships
Here we have a <p> element that's right next to an h3 which has the
version of our software.  We can make sure the website shows the
correct version.

#+begin_src html
<h3 class="reallynow">Version</h3>
<p>Version 0.2 "Dangle"</p>
#+end_src

#+srcname: simpleTestsRelationships
#+begin_src groovy :noweb tangle
assert $("h3.reallynow").siblings("p").find { it.text =~/Dangle/)
assert $("h3.reallynow").siblings("p").find { it.text =~/0.2/)
#+end_src

* See Also
- Geb
